### ISSUE TITLE
Find a better project name

### ISSUE THREAD

**Issue by hendrikb** [TheRealWolkenbruch/concept#3]
The title says it all, "dead man's switch" does not sound too well. Any better ideas on the name of our project?

**Comment by omarsotillo** [comment]
Some small fast names. Will update along the day.

- Covected
- Act-On Me
- Hilfe Times
- AdviceSwitch
- CovAlerts

**Comment by hendrikb** [comment]
I think it's not necessarily related to Covid-19 or so - so we should probably look out for a more broader name?

- Guardian (there's already a Newspaper with that name) / Guardian Angel
  - (interesting idea: rename the `Authority` entity in our Architecture to Guardian or GuardianAngel to make it less ... "hard")
- AreYouThere
- TheLink / TheBond / Bonds / Bonding / OurBonds
  - (interesting idea: we still haven't named the "service" where the Guardian that asks the Protege to provide feedback, this could be holistically named `Bond`)
- Beam / Ray / TheLight / ...
- Call Me / ...

**Comment by Thudilie** [comment]
AreYouThere -> nice one
raiseYourHand
LetMeKnow

**Comment by doggygit** [comment]
currently I am also in favor for *AreYouThere*

**Comment by hendrikb** [comment]
AreYouThere it is.
