### ISSUE TITLE
Progressive Web app vs Native application vs ...?

### ISSUE THREAD

**Issue by omarsotillo** [TheRealWolkenbruch/concept#4]
Hey! 👋🏻

### Background 🔙

From #2 we found a topic which for me is quite important in the matter of what we want to accomplish for our app. We have here the time constraint if we want to have something presentable by the end on the weekend

### Options 🔢 
- Web APP (react, vue.js)
- Native app (react-native)
- Both

### Proposal

Have a `PWA with mobile-first` design in mind. Also, the frontend parts can be divided into `present landing` and `app`.

#### Pros 

- Allow faster access to users (not installed app)
- Faster development (something we know)
- More welcome for hackathon people to try than downloading a website.
- Less infrastructure needed 

#### Cons 

- Not accessible for native features (like mobile notifications)
- ...

#### Action plan:

- 1st: `domain.com`: Using something already existent like [Cruip](https://cruip.com/demos/venus/) for example. Will already allow us to start showing things before anything is finished with little effort. We can upload this to [Vercel now](https://vercel.com/). Quite fast to be done.

- 2nd: `app.domain.com`: React focused app for development. I wanted to dig into [Next.js](https://nextjs.org/) 

- Optional(Mobile native app): If we have time start working on the native app. React native

This will allow having a PWA fast and probably within our time range. Afterwards, we can think of the native app or maybe start it during the weekend. 

#### Resources:

https://nextjs.org/
https://www.webfx.com/blog/web-design/native-app-vs-mobile-web-app-comparison/

**Comment by omarsotillo** [comment]
Checking https://github.com/d4l-data4life/covapp they use Stencil https://stenciljs.com/. Maybe we can use it as a selling point that we can integrate our app into that and therefore it simplifies the merging.

**Comment by hendrikb** [comment]
Let's do it like this. I was thinking that [React Native](https://reactnative.dev/docs/getting-started) also offers some HTML output for static webpages. This seems not to be true, so **let's forget about delivering classical mobile Apps** (so React Native is trashed for now due to time constraints) and go for mobile friendly websites.

@omarsotillo - can you give a bit more details what you mean with `present` & `landing` & `app` frontend-parts? What does cruip/vercel allow us to do?

**Comment by hendrikb** [comment]
@Thudilie @Garllon @doggygit - I think you should look into this discussion and make your points as well - if you want to influence the outcome of these decisions. :)

**Comment by doggygit** [comment]
I agree that React Native might not be doable with the time constraints.

Currently taking my first baby steps with React - there seems to be already enough stuff to learn for the weekend.

I am not sure how we can benefit of stencil.js . @omarsotillo  Perhaps explain it me/us in the video call in the afternoon?

**Comment by Thudilie** [comment]
@omarsotillo  thanks for the pros and cons. As you mentioned react seems to be the better choice than react native. To learn something about progressive webapps should also be nice but i guess this could be some kinde of 'should criteria'. Don't know how much needs to be done here. I'm looking forward to the videocall at  4:30PM  to gain some more informations.

**Comment by hendrikb** [comment]
@omarsotillo - you were opening this issue to make sure webapps vs native apps is clarified. are you satisfied with the outcomes? wanna take something from this discussions (stencil, etc.)? Feel free to close this issue, otherwise.

**Comment by omarsotillo** [comment]
@hendrikb It seems clear! 👯
