### ISSUE TITLE
Responsible People for Areas-of-Work

### ISSUE THREAD

**Issue by hendrikb** [TheRealWolkenbruch/concept#7]
Hey,

in order to have a good overview on Who & What - in the sense of: "Who makes sure that XYZ is being done. Not necessarily doing it alone or _at all_ - it makes sure to assign people to areas-of-work.

Here's my suggestion (format: Area-of-Work: **Responsible Person**, InterestedPerson1, InterestedPerson2, ...):

- Organizational/Hackathon Topics: @hendrikb 
- Overall Architecture Aspects: ???
- CI/CD, Deployment & Ops: @hendrikb, but need assistance 
- Dockerisation & Shipping: @hendrikb, but need assistance
- Backend API Design: ???
- Implementation main API/Backoffice functionality (we need lots of helping hands here!): ???
- Implementation Auth: ???
- Frontend for `Guardians` (in the Backoffice): ??? (probably also lots of hands here)
- Frontend/Forms for the `Wards` (Reachable through a Link in an Email): ???
- Design/Layout for Emails: ???

What have I forgotten? This can also act as some sort of beginning for the actual task assignment.

Please name your areas of work or make further suggestions.

Best,
Hendrik

**Comment by doggygit** [comment]
Offering to take responsibility (but I am fine to also only provide assistance):
* Auth implementation
* Backoffice
* API Design

I would be willing to provide assistance to every other topic if needed.

**Comment by Thudilie** [comment]
I offer myself/support for the frontend parts. :D
-> backgoffice, forms

**Comment by Thudilie** [comment]
@doggygit Auth in react frontend side or api? or both?

**Comment by randres1640** [comment]
Hi, Raúl here
I think I can contribute mainly in both Backend API Design And Implementation main API/Backoffice functionality areas, as InterestedPerson N. I prefer not to take responsibility on my first day.
I think I can help too solving problems in auth and CI areas too.

**Comment by hendrikb** [comment]
Alright Thanks for you feedback everyone, We were discussing areas-of-work in the video chat, I will update the docs accordingly and post a Merge Request here in a couple of minutes. :)
