### ISSUE TITLE
Setup Sequel

### ISSUE THREAD

**Issue by Garllon** [TheRealWolkenbruch/concept#9]
Database: SQLite

Entity Description: 
https://github.com/TheRealWolkenbruch/concept/blob/master/Entities.md

https://github.com/TheRealWolkenbruch/are-you-there-api/pull/1

**Comment by hendrikb** [comment]
@Garllon - before starting to code, please look at the https://github.com/TheRealWolkenbruch/concept/pull/13 pull request. We had to extend the data model and the stuff that you wrote into the description of this issue is not up-to-date anymore!

**Comment by Garllon** [comment]
I wrote it already 3 times, i only added one raw migration to show the
direction. :) Nothing more. Only that people can see: Ah this is how and
where i need to add a migration. I saw that the data model changed.
